services:
  receiver:
    container_name: receiver
    image: receiver
    restart: unless-stopped
    ports:
      - 11112:11112
    volumes:
      - /tmp/site/archive:/data/site/archive 
      - /tmp/site/raw:/data/site/raw 
      - /tmp/site/.arrived:/data/site/.arrived 
      - /tmp:/root/logs 
  
  fail2ban:
    container_name: fail2ban
    image: linuxserver/fail2ban:latest
    volumes:
      - /opt/fail2ban/config:/config
     
